<a href="https://colab.research.google.com/github/Techvolutions05/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/Anell_Santos_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [0]:
# YOUR WORK HERE
import pandas as pd
import numpy as np
from scipy.stats import chisquare
from scipy.stats import normaltest
from scipy.stats import kruskal
from scipy.stats import ttest_ind
from scipy import stats

In [3]:
!wget  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 19:38:23--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.03s   

2020-06-09 19:38:23 (699 KB/s) - ‘student.zip’ saved [20478/20478]



In [4]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [10]:
df = pd.read_csv('student-mat.csv', sep=';')
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [25]:
# Taking 2 variables that are dependent with each other
# Variable 1
df['famsup'].value_counts().sort_index()


no     153
yes    242
Name: famsup, dtype: int64

In [24]:
# Variable 2

df['famrel'].value_counts().sort_index()

1      8
2     18
3     68
4    195
5    106
Name: famrel, dtype: int64

In [29]:
contingency1 = pd.crosstab( df['famsup'], df['famrel'])
contingency1

famrel  1   2   3    4   5
famsup                    
no      3   7  29   67  47
yes     5  11  39  128  59

In [31]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency1)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 3.4205049164691195
p value 0.490068221674437
degrees of freedom 4
expected frequencies table [[  3.09873418   6.9721519   26.33924051  75.53164557  41.05822785]
 [  4.90126582  11.0278481   41.66075949 119.46835443  64.94177215]]


**Conclusion:**  The two variables are "dependent there's seem to be a correlation between the student's family support and student's family relationship.

In [12]:
# Taking 2 variables that are independent with each other
# Variable 1

df['guardian'].value_counts().sort_index()

father     90
mother    273
other      32
Name: guardian, dtype: int64

In [13]:
# Variable 2

df['Fjob'].value_counts().sort_index()

at_home      20
health       18
other       217
services    111
teacher      29
Name: Fjob, dtype: int64

In [17]:
# Using contingency to identify the dependency of both variables

contingency = pd.crosstab(df['Fjob'], df['guardian'])
contingency

guardian  father  mother  other
Fjob                           
at_home        5      13      2
health         7      10      1
other         34     164     19
services      35      66     10
teacher        9      20      0

In [19]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic:", chi2)
print("p value:", p_value)
print("degrees of freedom:",dof)
print("expected frequencies table:", expected)

chi2 statistic: 17.654569568050647
p value: 0.02397069057715143
degrees of freedom: 8
expected frequencies table: [[  4.55696203  13.82278481   1.62025316]
 [  4.10126582  12.44050633   1.45822785]
 [ 49.44303797 149.97721519  17.57974684]
 [ 25.29113924  76.7164557    8.99240506]
 [  6.60759494  20.04303797   2.34936709]]


**Conclusion:** There is not enough evidence to conclude that the job of the father and the guardian are associated (It does show any correlation). They might be independent.

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [33]:
# Testing from scratch
# Using the 'famsup' & 'famrel' samples
df['famsup'].value_counts()


yes    242
no     153
Name: famsup, dtype: int64

In [34]:
df['famrel'].value_counts()

4    195
5    106
3     68
2     18
1      8
Name: famrel, dtype: int64

In [42]:
observed = pd.crosstab(df['famrel'], df['famsup'])
observed

famsup  no  yes
famrel         
1        3    5
2        7   11
3       29   39
4       67  128
5       47   59

In [43]:
# Calculating the expected value

observed_with_margins = pd.crosstab(df['famrel'], df['famsup'], margins=True)

observed_with_margins

famsup   no  yes  All
famrel               
1         3    5    8
2         7   11   18
3        29   39   68
4        67  128  195
5        47   59  106
All     153  242  395

In [44]:
# Checking the value of the variable

observed = observed.values
observed

array([[  3,   5],
       [  7,  11],
       [ 29,  39],
       [ 67, 128],
       [ 47,  59]])

In [47]:
observed[4][1]

59

In [65]:
# (row_total)(column_total) / sample_size 

expected_row1_col1 = 8*153/395

expected_row1_col1


3.09873417721519

In [70]:
row_totals = df['famrel'].value_counts().sort_index().values

row_totals

array([  8,  18,  68, 195, 106])

In [71]:
col_totals = df['famsup'].value_counts().sort_index().values

col_totals

array([153, 242])

In [68]:
sample_size = df.shape[0]

sample_size

395

In [81]:
my_list = []

for i, row_total in enumerate(row_totals):
  row = []
  for j, column_total in enumerate(col_totals):
    expected_val  = ((column_total*row_total) / sample_size)
    row.append(expected_val)
  my_list.append(row)

my_list

[[3.09873417721519, 4.9012658227848105],
 [6.972151898734177, 11.027848101265823],
 [26.339240506329112, 41.66075949367089],
 [75.53164556962025, 119.46835443037975],
 [41.05822784810127, 64.94177215189873]]

In [89]:
expected = np.array(my_list).T

expected

array([[  3.09873418,   6.9721519 ,  26.33924051,  75.53164557,
         41.05822785],
       [  4.90126582,  11.0278481 ,  41.66075949, 119.46835443,
         64.94177215]])

In [93]:
observed

array([[  3,   5],
       [  7,  11],
       [ 29,  39],
       [ 67, 128],
       [ 47,  59]])

In [101]:
chi2 = (((observed.T - expected)**2) / expected).sum()

chi2

3.4205049164691195

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)